version: 2
jobs:
  build-and-test:

    macos:
      xcode: 9.3.1

    steps:
      - checkout

      - restore_cache:
          key: 1-carthage-{{checksum "Cartfile.resolved" }}

      - run: bin/setup

      - save_cache:
          key: 1-carthage-{{ checksum "Cartfile.resolved" }}
          paths: Carthage

      - run: bin/test

workflows:
  version: 2
  build-and-test:
    jobs:
      - build-and-test
