version: 2
jobs:
  build-and-test:

    macos:
      xcode: 9.3.1

    steps:
      - checkout
      - run: bin/setup
      - run: bin/test

workflows:
  version: 2
  build-and-test:
    jobs:
      - build-and-test
